### ISSUE TITLE
Setting

### ISSUE THREAD

**Issue by Alifian771** [rk797/zxmapper#1]
may i ask u for the best setting sir?

**Comment by rk797** [comment]
There are no "best" settings. The code is somewhat documented, look at what each setting does and configure it according to your needs. 

100 - 100 exponent factor and scale produces a linear input curve


I will release a hardware version of the remapper with many more features and better compatibility if there is enough interest.

**Comment by DanaiFPS** [comment]
Hello,
First of all I have to say nice work!
But i have a couple questions
1) How do I add extra mappings (cuz gui shows only W,A,S,D and sens)
2) I am currently using this for apex legends and sometimes left and right click bug and the weapon keeps shooting even if I dont press anything 
Thank you
